# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: barebonesboard_dev

test:
  <<: *default
  database: barebonesboard_test

production:
  <<: *default
  database: barebonesboard_prod
